git clone https://github.com/jaredhaight/PSAttack
git clone https://github.com/PowerShellEmpire/Empire
git clone https://github.com/dotcppfile/DAws
git clone https://github.com/samratashok/nishang
git clone https://github.com/zerosum0x0/koadic
git clone https://github.com/byt3bl33d3r/SILENTTRINITY
git clone https://github.com/JLospinoso/gargoyle
git clone https://github.com/stephenfewer/ReflectiveDLLInjection
git clone https://github.com/cobbr/PSAmsi/wiki/Conducting-AMSI-Scans
git clone https://github.com/GreatSCT/GreatSCT
git clone https://github.com/tokyoneon/Armor
git clone https://github.com/Techryptic/AV_Bypass
git clone https://github.com/CodeOfDark/Panda-Obfuscator
git clone https://github.com/two06/Inception
git clone https://github.com/api0cradle/LOLBAS
git clone https://github.com/subTee/AllTheThings
git clone https://github.com/m8r0wn/ldap_search
git clone https://github.com/invokethreatguy/AggressorCollection
git clone https://github.com/adaptivethreat/KeeThief
git clone https://github.com/ChrisTruncer/EyeWitness
git clone https://github.com/TryCatchHCF/Cloakify
git clone https://github.com/AlessandroZ/LaZagne
git clone https://github.com/HarmJ0y/ASREPRoast
git clone https://github.com/eladshamir/Internal-Monologue
git clone https://github.com/ustayready/CredSniper
git clone https://github.com/GoSecure/DLLPasswordFilterImplant
git clone https://github.com/GhostPack/SafetyKatz
git clone https://github.com/GhostPack/SharpDump
git clone https://github.com/djhohnstein/SharpWeb
git clone https://github.com/skelsec/pypykatz
git clone https://github.com/GhostPack/SharpDPAPI
git clone https://github.com/NetSPI/PowerUpSQL
git clone https://github.com/mdsecactivebreach/SharpShooter
git clone https://github.com/trustedsec/unicorn
git clone https://github.com/mattgwwalker/msg-extractor
git clone https://github.com/dafthack/MailSniper
git clone https://github.com/xorrior/EmailRaider
git clone https://github.com/SadProcessor/EmpireDog
git clone https://github.com/p3nt4/PowerShdll
git clone https://github.com/Mr-Un1k0d3r/PowerLessShell
git clone https://github.com/infosecn1nja/e2modrewrite
git clone https://github.com/api0cradle/BGInfo
git clone https://github.com/ytisf/PyExfil
git clone https://github.com/DakotaNelson/sneaky-creeper
git clone https://github.com/nerbix/Invoke-Exfiltration
git clone https://github.com/countercept/doublepulsar-detection-script
git clone https://github.com/Cn33liz/StarFighters
git clone https://github.com/sensepost/ruler
git clone https://github.com/tevora-threat/eternal_blue_powershell
git clone https://github.com/gentilkiwi/kekeo
git clone https://github.com/CoreSecurity/impacket
git clone https://github.com/bidord/pykek
git clone https://github.com/ChrisTruncer/WMIOps
git clone https://github.com/nidem/kerberoast
git clone https://github.com/danielbohannon/Invoke-Obfuscation
git clone https://github.com/danielbohannon/Invoke-CradleCrafter
git clone https://github.com/danielbohannon/Invoke-DOSfuscation
git clone https://github.com/GDSSecurity/Windows-Exploit-Suggester
git clone https://github.com/fdiskyou/PowerOPS
git clone https://github.com/infobyte/evilgrade
git clone https://github.com/elceef/bitlocker
git clone https://github.com/xorrior/RandomPS-Scripts
git clone https://github.com/Mr-Un1k0d3r/RedTeamPowershellScripts
git clone https://github.com/nccgroup/vlan-hopping---frogger
git clone https://github.com/xairy/kernel-exploits
git clone https://github.com/securestate/syringe
git clone https://github.com/putterpanda/mimikittenz
git clone https://github.com/vysec/ps1-toolkit
git clone https://github.com/mattifestation/WMI_Backdoor
git clone https://github.com/nccgroup/redsnarf
git clone https://github.com/fireeye/SessionGopher
git clone https://github.com/mefellows/winrm-powershell
git clone https://github.com/silentbreaksec/Throwback
git clone https://github.com/Kevin-Robertson/Inveigh
git clone https://github.com/lazywinadmin/PowerShell
git clone https://github.com/denandz/KeeFarce
git clone https://github.com/novnc/noVNC
git clone https://github.com/jaredcatkinson/EvilNetConnectionWMIProvider
git clone https://github.com/r00t-3xp10it/FakeImageExploiter
git clone https://github.com/DamonMohammadbagher/NativePayload_Image
git clone https://github.com/n1nj4sec/memorpy
git clone https://github.com/tomerfiliba/rpyc
git clone https://github.com/xorrior/RemoteRecon
git clone https://github.com/nil0x42/phpsploit
git clone https://github.com/decoder-it/psportfwd
git clone https://github.com/PowerShellMafia/PowerSploit
git clone https://github.com/homjxi0e/PowerAvails
git clone https://github.com/GhostPack/SharpRoast
git clone https://github.com/GhostPack/Seatbelt
git clone https://github.com/foxglovesec/RottenPotato 
git clone https://github.com/FuzzySecurity/Unix-PrivEsc
git clone https://github.com/0x90/lpe-arsenal
git clone https://github.com/1N3/PrivEsc
git clone https://github.com/foxglovesec/Potato
git clone https://github.com/AlessandroZ/BeRoot
git clone https://github.com/GhostPack/SharpUp
git clone https://github.com/trustedsec/trevorc2
git clone https://github.com/PyroTek3/PowerShell-AD-Recon
git clone https://github.com/aboul3la/Sublist3r
git clone https://github.com/az0ne/nmap-scada
git clone https://github.com/infosecn1nja/e2modrewrite
git clone https://github.com/ChrisTruncer/PenTestScripts
git clone https://github.com/Shellntel/scripts
git clone https://github.com/rvrsh3ll/Misc-Powershell-Scripts
git clone https://github.com/edwardz246003/IIS_exploit
git clone https://github.com/samratashok/Kautilya
git clone https://github.com/mattifestation/PowerWorm
git clone https://github.com/commixproject/commix
git clone https://github.com/dannagle/packetsender
git clone https://github.com/macubergeek/gitlist
git clone https://github.com/devttys0/littleblackbox
git clone https://github.com/rapid7/ssh-badkeys
git clone https://github.com/0x90/kali-scripts
git clone https://github.com/jshaw87/Scripts
git clone https://github.com/rossja/pentools
git clone https://github.com/MooseDojo/apt2
git clone https://github.com/mubix/vt-notify
git clone https://github.com/yudai/gotty
git clone https://github.com/jivoi/pentest
git clone https://github.com/darkoperator/Posh-SSH
git clone https://github.com/P3t3rp4rk3r/My_Dirty_Scripts
git clone https://github.com/thoemmi/7Zip4Powershell
git clone https://github.com/ssOleg/Useful_code
git clone https://github.com/TryCatchHCF/DumpsterFire
git clone https://github.com/mgeeky/Penetration-Testing-Tools
git clone https://github.com/decoder-it/psportfwd/blob/master/portfwd.ps1
git clone https://github.com/fdiskyou/PSShell
git clone https://github.com/hfiref0x/UACME
git clone https://github.com/enigma0x3/Misc-PowerShell-Stuff
git clone https://github.com/bartblaze/dccwUACBypass
git clone https://gist.github.com/mattifestation/b4072a066574caccfa07fcf723952d54
git clone https://github.com/0xbadjuju/Tokenvator
git clone https://github.com/joaomatosf/jexboss
git clone https://github.com/s0lst1c3/eaphammer
git clone https://github.com/GhostPack/SharpRoast
git clone https://github.com/GhostPack/SharpUp
git clone https://github.com/GhostPack/Seatbelt
git clone https://github.com/GhostPack/SharpDump
git clone https://github.com/pwndizzle/c-sharp-memory-injection
git clone https://github.com/eladshamir/Internal-Monologue
git clone https://github.com/0xbadjuju/Tokenvator
git clone https://github.com/ambray/ProcessHollowing
git clone https://github.com/ThunderGunExpress/OutlookToolbox
git clone https://github.com/xorrior/Random-CSharpTools
git clone https://github.com/BloodHoundAD/SharpHound
git clone https://github.com/jephthai/OpenPasswordFilter
git clone https://github.com/zerosum0x0/RunShellcode
git clone https://github.com/Arno0x/CSharpScripts
git clone https://github.com/jaredhaight/PSAttack
git clone https://github.com/stufus/reconerator
git clone https://github.com/DissectMalware/ClipboardWatcher
git clone https://github.com/nettitude/SharpSocks
git clone https://github.com/jaredhaight/SharpAttack
git clone https://github.com/anthemtotheego/SharpCradle
git clone https://github.com/SpiderLabs/SharpCompile
git clone https://github.com/P1CKLES/SharpBox
git clone https://github.com/0xbadjuju/TellMeYourSecrets
git clone https://github.com/tandasat/DotNetHooking
git clone https://github.com/leoloobeek/csharp
git clone https://github.com/cobbr/SharpSploit
git clone https://github.com/djhohnstein/SharpWeb
git clone https://github.com/malcomvetter/CSExec
git clone https://github.com/GhostPack/SharpWMI
git clone https://github.com/GhostPack/SharpDPAPI
git clone https://github.com/securestate/eapeak
git clone https://github.com/trustedsec/ptf.git
git clone https://github.com/portcullislabs/rdp-sec-check.git
git clone https://github.com/govolution/avet.git
git clone https://github.com/bitsadmin/wesng.git
git clone https://github.com/Wh1t3Rh1n0/air-hammer.git
git clone https://github.com/khast3x/Redcloud.git
git cleon https://github.com/fox-it/adconnectdump.git


